---
- name: Install Docker
  hosts: docker
  become: true

  tasks:
    - name: Add Docker repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker Stable repository
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
        state: present

    - name: Update DNF
      ansible.builtin.dnf:
        update_cache: true
        state: latest

    - name: Install Docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started

- name: Launch arcane qual
  hosts: qual:&docker
  become: true

  tasks:
    - name: Create arcane data volume
      community.docker.docker_volume:
        name: arcane_data

    - name: Launch arcane container
      community.docker.docker_container:
        name: arcane
        image: ghcr.io/getarcaneapp/arcane:v1.14.1
        ports:
          - 9000:3552
        restart: yes
        restart_policy: always
        volumes:
          - arcane_data:/app/data
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - name: front
        env:
          PUID: "0"
          PGID: "0"
          ENCRYPTION_KEY: "{{ arcane_encryption_key | string }}"
          JWT_SECRET: "{{ arcane_jwt_key | string }}"
        state: started
