---
- name: Mount NFS shares
  hosts: qual:&docker
  become: true

  tasks:
    - name: Mount NFS share
      ansible.posix.mount:
        path: /mnt/Data
        src: 192.168.20.248:/mnt/Data
        fstype: nfs4
        state: mounted


