services:
  media:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - jellyfin_config:/config
      - /mnt/Multimedia/Medias/Series:/media/Series
      - /mnt/Multimedia/Medias/Films:/media/Films
      - /mnt/Multimedia/Medias/Animes:/media/Animes
      - /mnt/Multimedia/Medias/Music:/media/Music
    ports:
      - 8096:8096
    networks:
      - front

  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    restart: unless-stopped
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - deluge_config:/config
      - /mnt/Multimedia/Downloads:/downloads
    networks:
      - front

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - sonarr_config:/config
      - /mnt/Multimedia/Downloads/Series:/downloads/Series
      - /mnt/Multimedia/Downloads/Animes:/downloads/Animes
      - /mnt/Multimedia/Medias/Series:/series
      - /mnt/Multimedia/Medias/Animes:/animes
    networks:
      - front

volumes:
  jellyfin_config:
  deluge_config:
  sonarr_config:

networks:
  front:
    external: true
