services:
  media:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - jellyfin_config:/config
      - /mnt/Multimedia/Medias/Series:/media/Series
      - /mnt/Multimedia/Medias/Films:/media/Films
      - /mnt/Multimedia/Medias/Animes:/media/Animes
      - /mnt/Multimedia/Medias/Music:/media/Music
    ports:
      - 8096:8096
    networks:
      - front

  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - deluge_config:/config
      - /mnt/Multimedia/Downloads:/downloads
      - /mnt/Multimedia/Downloads/Series:/downloads/Series
      - /mnt/Multimedia/Downloads/Animes:/downloads/Animes
      - /mnt/Multimedia/Downloads/Films:/downloads/Films
      - /mnt/Multimedia/Downloads/Music:/downloads/Music
    networks:
      - front

volumes:
  jellyfin_config:
  deluge_config:

networks:
  front:
    external: true
