services:
  media:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - jellyfin_config:/config
      - /mnt/Multimedia/Medias/Series:/media/Series
      - /mnt/Multimedia/Medias/Films:/media/Films
      - /mnt/Multimedia/Medias/Animes:/media/Animes
      - /mnt/Multimedia/Medias/Music:/media/Music
    ports:
      - 8096:8096
    networks:
      - front

  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    restart: unless-stopped
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - deluge_config:/config
      - /mnt/Multimedia/Downloads:/downloads
    networks:
      - front

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - sonarr_config:/config
      - /mnt/Multimedia/Downloads/Series:/downloads/Series
      - /mnt/Multimedia/Downloads/Animes:/downloads/Animes
      - /mnt/Multimedia/Medias/Series:/series
      - /mnt/Multimedia/Medias/Animes:/animes
    networks:
      - front

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - radarr_config:/config
      - /mnt/Multimedia/Downloads/Films:/downloads/Films
      - /mnt/Multimedia/Medias/Films:/films
    networks:
      - front

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - lidarr_config:/config
      - /mnt/Multimedia/Downloads/Music:/downloads/Music
      - /mnt/Multimedia/Medias/Music:/music
    networks:
      - front

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - prowlarr_config:/config
    networks:
      - front

  jellyseerr:
    image: fallenbagel/jellyseerr:preview-OIDC
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - 5055:5055
    environment:
      - TZ=Europe/Paris
    volumes:
      - jellyseerr_config:/app/config
    networks:
      - front



volumes:
  jellyfin_config:
  deluge_config:
  sonarr_config:
  radarr_config:
  lidarr_config:
  prowlarr_config:
  jellyseerr_config:

networks:
  front:
    external: true
