services:
  media:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - jellyfin_config:/config
      - /mnt/Multimedia/Series:/media/Series
      - /mnt/Multimedia/Films:/media/Films
      - /mnt/Multimedia/Animes:/media/Animes
      - /mnt/Multimedia/Music:/media/Music
    ports:
      - 8096:8096
    networks:
      - front

  torrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - WEBUI_PORT=9091
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent_config:/config
      - /mnt/Downloads:/downloads
    ports:
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - front

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - sonarr_config:/config
      - /mnt/Downloads/Series:/downloads/Series
      - /mnt/Downloads/Animes:/downloads/Animes
      - /mnt/Multimedia/Series:/series
      - /mnt/Multimedia/Animes:/animes
    networks:
      - front

  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - radarr_config:/config
      - /mnt/Downloads/Films:/downloads/Films
      - /mnt/Multimedia/Films:/films
    networks:
      - front

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.2-nightly
    container_name: lidarr
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - lidarr_config:/config
      - /mnt/Downloads/Music:/downloads/Music
      - /mnt/Multimedia/Music:/music
    networks:
      - front

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - prowlarr_config:/config
    networks:
      - front

  jellyseerr:
    image: fallenbagel/jellyseerr:preview-OIDC
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - 5055:5055
    environment:
      - TZ=Europe/Paris
    volumes:
      - jellyseerr_config:/app/config
    networks:
      - front



volumes:
  jellyfin_config:
  qbittorrent_config:
  sonarr_config:
  radarr_config:
  lidarr_config:
  prowlarr_config:
  jellyseerr_config:

networks:
  front:
    external: true
